//in JSX (React) it is possible conditional rendering in different ways
// we can use ternary operator or an if/else statement

//getNum function return a random number from 1 to 10
function getNum() {
  return Math.floor(Math.random() * 10) + 1;
}

//NumPicker component will change is <p> tag
//according to the number generated by getNum()
//here we use the Ternary Operator to conditionally render a
//<p> tag or another
class NumPicker extends React.Component {
  render() {
    const num = getNum();
    return (
      <div>
        <h1>Your number is {num}</h1>
        <p>{num === 7 ? 'Congrats!' : 'Not Lucky Enough!'}</p>
        {num === 7 ? <img src="https://i.giphy.com/media/nXxOjZrbnbRxS/giphy.webp" /> : null}
      </div>
    );
  }
}

ReactDOM.render(<NumPicker />, document.getElementById('root'));
